# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O3 -pipe"
COMMON_FLAGS="${COMMON_FLAGS} -fno-plt -fstack-protector-strong -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
# COMMON_FLAGS="${COMMON_FLAGS} -flto=auto"
LDFLAGS="${LDFLAGS} -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native -C opt-level=3 -C codegen-units=1"

# Make Options
# 
# enable this when using tty / terminal mode
# MAKEOPTS="-j17 -l16"
# enable this when on GUI / desktop or slow compilation
MAKEOPTS="-j12 -l12"

# USE Flags
USE="X networkmanager zstd lzma lz4 threads vulkan opengl wayland jpeg png webp pipewire wireplumber udev dbus elogind gtk alsa"
USE="${USE} dist-kernel"
USE="${USE} apparmor"
USE="-branding -flatpak -gnome -oss -jack -jack2 -consolekit -qt -qt5 -qt6 -qtbase -kde -systemd -bluetooth -cups"

# Features Flags
FEATURES="${FEATURES} parallel-fetch parallel-install candy"

# ACCEPT KEYWORDS AND LICENSE
ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="amd64"

# Grub flags
GRUB_PLATFORMS="efi-64"


PORTAGE_COMPRESS="zstd"

EMERGE_DEFAULT_OPTS="--jobs=8 --load-average=12"
EMERGE_DEFAULT_OPTS="${EMERGE_DEFAULT_OPTS} --usepkg --buildpkg"

PORTAGE_COMPRESS="zstd"
PORTAGE_COMPRESS_FLAGS="-19 --threads=0"

PKGDIR="/var/cache/binpkgs"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
