# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[noverlay]
location = /var/db/repos/noverlay
sync-type = git
sync-uri = https://github.com/noqmorien/noverlay
