# font=IosevkaTerm Nerd Font Mono:size=7.65
term=xterm-256color
font=SpaceMono Nerd Font Mono:size=8.15
pad=4x4 center
dpi-aware=yes
gamma-correct-blending=yes
bold-text-in-bright=yes
workers=17

[mouse]
hide-when-typing=yes

[url]
launch=xdg-open ${url}
osc8-underline=url-mode

[key-bindings]
show-urls-launch=Control+Shift+o
show-urls-copy=Control+Shift+y
